### ISSUE TITLE
В редакторе кнопка UPPERCASE не работает

### ISSUE THREAD

**Issue by alinastart** [YarGU-Demidov/math-site#272]

**Comment by mokeev1995** [comment]
необходимо добавить стиль в файл стилей 
```css
.fr-text-uppercase {
    text-transform: uppercase;
}
```
